// vm/op_prof.rs — `Op` の宣言順インデックスと名前表（feature = "prof" 専用・自動生成）。
//
// 生成元: src/vm/op.rs の `enum Op` の宣言順。**手で書き換えない**。
// op を追加/削除したら再生成すること（`op_index` にワイルドカードを置いていないので、
// ずれたまま `cargo build --features prof` が通ることはない）。
//
// ⚠⚠ **「通ることはない」のは `--features prof` でビルドしたときだけ**（#69 で判明）。
// 既定ビルドではこのファイルごと消えるので、#68 が `EnumDef` を足したとき**誰も気づかず**、
// `--features prof` が壊れたまま残っていた。⇒ **op を足したら
// `cargo build --features prof` と `--features tw_stats` も通すこと**（5 点セットの外側）。

use super::op::Op;

/// 宣言順の op 名（`op_index` の戻り値でそのまま索引できる）。
pub const OP_NAMES: [&str; 87] = [
    "Const",
    "Nil",
    "LoadLocal",
    "LoadGlobal",
    "StoreGlobal",
    "StoreName",
    "StoreLocal",
    "StoreLocalDeepCopy",
    "StoreLocalCopyFreeze",
    "StoreLocalFreezeInstance",
    "StoreLocalFromIdent",
    "CallBuiltinKw",
    "CallMethodKw",
    "StaticInit",
    "StaticStore",
    "LoadStatic",
    "StoreStatic",
    "LoadCell",
    "StoreCell",
    "StoreCellDeepCopy",
    "Pop",
    "Bin",
    "BinLocalLocal",
    "BinLocalConst",
    "IntBinLL",
    "IntBinLC",
    "FloatBinLL",
    "FloatBinLC",
    "IntBinSS",
    "FloatBinSS",
    "Un",
    "GetAttr",
    "SetAttr",
    "Swap",
    "CallMethodLocal",
    "GetAttrLocal",
    "IsType",
    "MustBe",
    "Cast",
    "CallBuiltin",
    "GetIter",
    "ForIter",
    "Jump",
    "JumpIfFalse",
    "JumpIfFalseOrPop",
    "JumpIfTrueOrPop",
    "Call",
    "CallMethod",
    "Return",
    "ReturnNil",
    "SetupTry",
    "PopTry",
    "Raise",
    "Reraise",
    "Dup",
    "ExcMatch",
    "CheckBlockReturn",
    "CheckLoopYield",
    "Fail",
    "BuildEmptyList",
    "ListAppendLocal",
    "ListOrNone",
    "LoadName",
    "DeclareName",
    "MakeFn",
    "EnumDef",
    "UnpackTuple",
    "LetTuple",
    "FreezeVar",
    "EventSubscribe",
    "EventUnsubscribe",
    "CallKw",
    "CallTemplate",
    "BuildSlice",
    "DeclareGlobal",
    "LoadSelfClass",
    "GetTraitAttr",
    "SetTraitAttr",
    "BreakPoint",
    "Subscript",
    "SetIndex",
    "BuildList",
    "BuildTuple",
    "BuildSet",
    "BuildDict",
    "Yield",
    "AsyncSubmit",
];

/// `Op` を宣言順のインデックスへ落とす。
///
/// ⚠ ワイルドカードアームを置かない（op を足したときにコンパイルエラーにするため）。
#[inline(always)]
pub fn op_index(op: &Op) -> u8 {
    match op {
        Op::Const { .. } => 0,
        Op::Nil => 1,
        Op::LoadLocal { .. } => 2,
        Op::LoadGlobal { .. } => 3,
        Op::StoreGlobal { .. } => 4,
        Op::StoreName { .. } => 5,
        Op::StoreLocal { .. } => 6,
        Op::StoreLocalDeepCopy { .. } => 7,
        Op::StoreLocalCopyFreeze { .. } => 8,
        Op::StoreLocalFreezeInstance { .. } => 9,
        Op::StoreLocalFromIdent { .. } => 10,
        Op::CallBuiltinKw { .. } => 11,
        Op::CallMethodKw { .. } => 12,
        Op::StaticInit { .. } => 13,
        Op::StaticStore { .. } => 14,
        Op::LoadStatic { .. } => 15,
        Op::StoreStatic { .. } => 16,
        Op::LoadCell { .. } => 17,
        Op::StoreCell { .. } => 18,
        Op::StoreCellDeepCopy { .. } => 19,
        Op::Pop => 20,
        Op::Bin { .. } => 21,
        Op::BinLocalLocal { .. } => 22,
        Op::BinLocalConst { .. } => 23,
        Op::IntBinLL { .. } => 24,
        Op::IntBinLC { .. } => 25,
        Op::FloatBinLL { .. } => 26,
        Op::FloatBinLC { .. } => 27,
        Op::IntBinSS { .. } => 28,
        Op::FloatBinSS { .. } => 29,
        Op::Un { .. } => 30,
        Op::GetAttr { .. } => 31,
        Op::SetAttr { .. } => 32,
        Op::Swap => 33,
        Op::CallMethodLocal { .. } => 34,
        Op::GetAttrLocal { .. } => 35,
        Op::IsType { .. } => 36,
        Op::MustBe { .. } => 37,
        Op::Cast { .. } => 38,
        Op::CallBuiltin { .. } => 39,
        Op::GetIter => 40,
        Op::ForIter { .. } => 41,
        Op::Jump { .. } => 42,
        Op::JumpIfFalse { .. } => 43,
        Op::JumpIfFalseOrPop { .. } => 44,
        Op::JumpIfTrueOrPop { .. } => 45,
        Op::Call { .. } => 46,
        Op::CallMethod { .. } => 47,
        Op::Return => 48,
        Op::ReturnNil => 49,
        Op::SetupTry { .. } => 50,
        Op::PopTry => 51,
        Op::Raise { .. } => 52,
        Op::Reraise => 53,
        Op::Dup => 54,
        Op::ExcMatch { .. } => 55,
        Op::CheckBlockReturn { .. } => 56,
        Op::CheckLoopYield { .. } => 57,
        Op::Fail { .. } => 58,
        Op::BuildEmptyList => 59,
        Op::ListAppendLocal { .. } => 60,
        Op::ListOrNone => 61,
        Op::LoadName { .. } => 62,
        Op::DeclareName { .. } => 63,
        Op::MakeFn { .. } => 64,
        Op::EnumDef { .. } => 65,
        Op::UnpackTuple { .. } => 66,
        Op::LetTuple { .. } => 67,
        Op::FreezeVar { .. } => 68,
        Op::EventSubscribe { .. } => 69,
        Op::EventUnsubscribe => 70,
        Op::CallKw { .. } => 71,
        Op::CallTemplate { .. } => 72,
        Op::BuildSlice => 73,
        Op::DeclareGlobal { .. } => 74,
        Op::LoadSelfClass => 75,
        Op::GetTraitAttr { .. } => 76,
        Op::SetTraitAttr { .. } => 77,
        Op::BreakPoint { .. } => 78,
        Op::Subscript => 79,
        Op::SetIndex => 80,
        Op::BuildList { .. } => 81,
        Op::BuildTuple { .. } => 82,
        Op::BuildSet { .. } => 83,
        Op::BuildDict { .. } => 84,
        Op::Yield => 85,
        Op::AsyncSubmit { .. } => 86,
    }
}
