// codegen.rs — Handle-based Rust source generator for tl module functions.
//
// All values crossing the module boundary are `i64` handles into a thread-local
// value arena owned by the interpreter (see interpreter/native_api.rs).
//
// The generated code receives a `TlCallbacks` struct pointer via `tl_init(cb)`
// at load time. Every value operation (arithmetic, attr access, function calls,
// iteration) routes through these callbacks, so ALL types are supported.
//
// Eligibility: a function is compiled natively when its body contains none of:
//   - yield / yield from (generator functions)
//   - inner fn / gen definitions (closures)
//   - try / except / raise (exception handling)
//   - block_return / loop_yield (block expressions)
//   - keyword arguments in any call site
//   - static mut declarations
//   - import statements

use std::collections::{HashMap, HashSet};

use crate::ast::{BinOp, CallArg, Expr, MatchPattern, Param, Stmt, UnaryOp};

// ── Public types ─────────────────────────────────────────────────────────────

/// ネイティブにエクスポートされた関数のメタデータ。
/// 関数名とパラメータ数を保持し、DLL呼び出し時に使用される。
#[derive(Debug, Clone)]
pub struct FnExport {
    pub name: String,
    pub n_params: usize,
}

// ── Module header emitted at the top of every generated Rust file ─────────────

const MODULE_HEADER: &str = r#"// Auto-generated by test_lang compiler — do not edit.
#![allow(dead_code, unused_variables, unused_assignments, non_snake_case, unused_unsafe)]

// ── Handle constants ─────────────────────────────────────────────────────────
const TL_NONE: i64 = 0;
const TL_TRUE: i64 = 1;
const TL_FALSE: i64 = 2;
const TL_STOP_ITER: i64 = -1;

// ── BinOp codes ───────────────────────────────────────────────────────────────
const OP_ADD: i32 = 0;
const OP_SUB: i32 = 1;
const OP_MUL: i32 = 2;
const OP_DIV: i32 = 3;
const OP_FLOOR_DIV: i32 = 4;
const OP_MOD: i32 = 5;
const OP_POW: i32 = 6;
const OP_EQ: i32 = 7;
const OP_NE: i32 = 8;
const OP_LT: i32 = 9;
const OP_LE: i32 = 10;
const OP_GT: i32 = 11;
const OP_GE: i32 = 12;
const OP_BIT_AND: i32 = 13;
const OP_BIT_OR: i32 = 14;
const OP_BIT_XOR: i32 = 15;
const OP_LSHIFT: i32 = 16;
const OP_RSHIFT: i32 = 17;
const OP_IN: i32 = 18;
const OP_NOTIN: i32 = 19;

// ── UnaryOp codes ─────────────────────────────────────────────────────────────
const UOP_NEG: i32 = 0;
const UOP_NOT: i32 = 1;
const UOP_BIT_NOT: i32 = 2;

// ── TlCallbacks struct (must match interpreter::native_api::TlCallbacks) ─────
#[repr(C)]
struct TlCallbacks {
    make_int:   unsafe extern "C" fn(i64) -> i64,
    make_float: unsafe extern "C" fn(f64) -> i64,
    make_bool:  unsafe extern "C" fn(i32) -> i64,
    make_str:   unsafe extern "C" fn(*const u8, i32) -> i64,
    make_list:  unsafe extern "C" fn(*const i64, i32) -> i64,
    make_tuple: unsafe extern "C" fn(*const i64, i32) -> i64,
    make_dict:  unsafe extern "C" fn(*const i64, *const i64, i32) -> i64,
    make_none:  unsafe extern "C" fn() -> i64,
    is_truthy:  unsafe extern "C" fn(i64) -> i32,
    binop:      unsafe extern "C" fn(i32, i64, i64) -> i64,
    unop:       unsafe extern "C" fn(i32, i64) -> i64,
    call_fn:    unsafe extern "C" fn(i64, *const i64, i32) -> i64,
    get_attr:   unsafe extern "C" fn(i64, *const u8, i32) -> i64,
    set_attr:   unsafe extern "C" fn(i64, *const u8, i32, i64),
    subscript:  unsafe extern "C" fn(i64, i64) -> i64,
    get_global: unsafe extern "C" fn(*const u8, i32) -> i64,
    iter_from:     unsafe extern "C" fn(i64) -> i64,
    iter_next:     unsafe extern "C" fn(i64) -> i64,
    is_type:       unsafe extern "C" fn(i64, *const u8, i32) -> i64,
    arena_save:    unsafe extern "C" fn() -> u64,
    arena_compact: unsafe extern "C" fn(i64, u64) -> i64,
    compact_many:  unsafe extern "C" fn(*const i64, i32, u64, *mut i64),
    to_int:        unsafe extern "C" fn(i64) -> i64,
    to_float:      unsafe extern "C" fn(i64) -> f64,
    deep_copy:     unsafe extern "C" fn(i64) -> i64,
    to_cstr:       unsafe extern "C" fn(i64) -> *const u8,
    write_handle:  unsafe extern "C" fn(i64, i64),
}

static mut CB: *const TlCallbacks = std::ptr::null();

#[no_mangle]
pub unsafe extern "C" fn tl_init(cb: *const TlCallbacks) {
    CB = cb;
}

// ── Inline helpers wrapping CB function pointers ───────────────────────────────
#[inline(always)] unsafe fn cb_make_int(n: i64) -> i64   { ((*CB).make_int)(n) }
#[inline(always)] unsafe fn cb_make_float(f: f64) -> i64  { ((*CB).make_float)(f) }
#[inline(always)] unsafe fn cb_make_bool(b: bool) -> i64  { ((*CB).make_bool)(if b { 1 } else { 0 }) }
#[inline(always)] unsafe fn cb_make_str(s: &[u8]) -> i64  { ((*CB).make_str)(s.as_ptr(), s.len() as i32) }
#[inline(always)] unsafe fn cb_make_none() -> i64          { TL_NONE }
#[inline(always)] unsafe fn cb_is_truthy(h: i64) -> bool   { ((*CB).is_truthy)(h) != 0 }
#[inline(always)] unsafe fn cb_binop(op: i32, a: i64, b: i64) -> i64 { ((*CB).binop)(op, a, b) }
#[inline(always)] unsafe fn cb_unop(op: i32, a: i64) -> i64           { ((*CB).unop)(op, a) }
#[inline(always)] unsafe fn cb_call(fn_h: i64, args: &[i64]) -> i64   { ((*CB).call_fn)(fn_h, args.as_ptr(), args.len() as i32) }
#[inline(always)] unsafe fn cb_get_attr(obj: i64, name: &[u8]) -> i64 { ((*CB).get_attr)(obj, name.as_ptr(), name.len() as i32) }
#[inline(always)] unsafe fn cb_set_attr(obj: i64, name: &[u8], val: i64) { ((*CB).set_attr)(obj, name.as_ptr(), name.len() as i32, val) }
#[inline(always)] unsafe fn cb_subscript(obj: i64, key: i64) -> i64   { ((*CB).subscript)(obj, key) }
#[inline(always)] unsafe fn cb_get_global(name: &[u8]) -> i64         { ((*CB).get_global)(name.as_ptr(), name.len() as i32) }
#[inline(always)] unsafe fn cb_iter_from(obj: i64) -> i64             { ((*CB).iter_from)(obj) }
#[inline(always)] unsafe fn cb_iter_next(iter: i64) -> i64            { ((*CB).iter_next)(iter) }
#[inline(always)] unsafe fn cb_is_type(obj: i64, name: &[u8]) -> i64  { ((*CB).is_type)(obj, name.as_ptr(), name.len() as i32) }
#[inline(always)] unsafe fn cb_make_list(items: &[i64]) -> i64        { ((*CB).make_list)(items.as_ptr(), items.len() as i32) }
#[inline(always)] unsafe fn cb_make_tuple(items: &[i64]) -> i64       { ((*CB).make_tuple)(items.as_ptr(), items.len() as i32) }
#[inline(always)] unsafe fn cb_make_dict(ks: &[i64], vs: &[i64]) -> i64 { ((*CB).make_dict)(ks.as_ptr(), vs.as_ptr(), ks.len() as i32) }
#[inline(always)] unsafe fn cb_arena_save() -> u64                       { ((*CB).arena_save)() }
#[inline(always)] unsafe fn cb_arena_compact(h: i64, s: u64) -> i64      { ((*CB).arena_compact)(h, s) }
#[inline(always)] unsafe fn cb_compact_many(i: *const i64, n: i32, s: u64, o: *mut i64) { ((*CB).compact_many)(i, n, s, o) }
#[inline(always)] unsafe fn cb_to_int(h: i64) -> i64                     { ((*CB).to_int)(h) }
#[inline(always)] unsafe fn cb_to_float(h: i64) -> f64                   { ((*CB).to_float)(h) }
#[inline(always)] unsafe fn cb_deep_copy(h: i64) -> i64                  { ((*CB).deep_copy)(h) }

// ── Pure-Rust helpers for Python-compatible int floor-div and mod ────────────
#[inline(always)] fn _tl_idiv(a: i64, b: i64) -> i64 {
    let d = a / b; let r = a % b;
    if r != 0 && (r < 0) != (b < 0) { d - 1 } else { d }
}
#[inline(always)] fn _tl_imod(a: i64, b: i64) -> i64 {
    let r = a % b;
    if r != 0 && (r < 0) != (b < 0) { r + b } else { r }
}

"#;

// ── Native type system ────────────────────────────────────────────────────────

/// 生成された変数・式のRustストレージ型。
/// `Bool` は比較結果の一時型としてのみ使用され、変数は常に `Int`・`Float`・`Handle` として格納される。
#[derive(Clone, Copy, PartialEq, Debug)]
enum Ty {
    Int,
    Float,
    Bool,
    Handle,
}

/// モジュール関数のシグネチャ: 戻り値の型と各パラメータの可変性フラグ。
struct FnSig {
    ret: Ty,
    /// `true` = `mut` パラメータ, `false` = `let` パラメータ（イミュータブル、呼び出し時にディープコピーが必要）。
    param_mutabilities: Vec<bool>,
}

/// 型アノテーション文字列から対応するネイティブ型 `Ty` を返す。
fn ann_ty(s: Option<&str>) -> Ty {
    match s {
        Some("int") => Ty::Int,
        Some("float") => Ty::Float,
        Some("bool") => Ty::Handle, // bool values are TL_TRUE/TL_FALSE handles
        _ => Ty::Handle,
    }
}

/// 式の型をストレージ型に変換する: `Bool` → `Handle`（TL_TRUE/TL_FALSE）、それ以外は変化なし。
fn store_ty(t: Ty) -> Ty {
    if t == Ty::Bool {
        Ty::Handle
    } else {
        t
    }
}

/// 任意の型のコードをハンドル (`i64`) に変換するRustコードを生成する。
fn coerce_to_h(code: &str, t: Ty) -> String {
    match t {
        Ty::Int => format!("cb_make_int({code})"),
        Ty::Float => format!("cb_make_float({code})"),
        Ty::Bool => format!("(if {code} {{ TL_TRUE }} else {{ TL_FALSE }})"),
        Ty::Handle => code.to_string(),
    }
}

/// 任意の型のコードを整数 (`i64`) に変換するRustコードを生成する。
fn coerce_to_i(code: &str, t: Ty) -> String {
    match t {
        Ty::Int => code.to_string(),
        Ty::Float => format!("({code} as i64)"),
        Ty::Bool => format!("(if {code} {{ 1i64 }} else {{ 0i64 }})"),
        Ty::Handle => format!("cb_to_int({code})"),
    }
}

/// 任意の型のコードを浮動小数点数 (`f64`) に変換するRustコードを生成する。
fn coerce_to_f(code: &str, t: Ty) -> String {
    match t {
        Ty::Float => code.to_string(),
        Ty::Int => format!("({code} as f64)"),
        Ty::Bool => format!("(if {code} {{ 1.0f64 }} else {{ 0.0f64 }})"),
        Ty::Handle => format!("cb_to_float({code})"),
    }
}

/// 任意の型のコードを条件式 (`bool`) に変換するRustコードを生成する。
fn coerce_to_cond(code: &str, t: Ty) -> String {
    match t {
        Ty::Bool => code.to_string(),
        Ty::Int => format!("({code} != 0i64)"),
        Ty::Float => format!("({code} != 0.0f64)"),
        Ty::Handle => format!("cb_is_truthy({code})"),
    }
}

/// 二項演算子を型特化されたRustコードに変換し、結果の型も返す。
/// いずれかの側が `Handle` の場合は `cb_binop` にフォールバックする。
fn specialize_binop(op: &BinOp, l: &str, lt: Ty, r: &str, rt: Ty) -> (String, Ty) {
    // If either side is a Handle we can't specialize — fall back to cb_binop.
    if lt == Ty::Handle || rt == Ty::Handle {
        let oc = binop_code(op);
        return (
            format!(
                "cb_binop({oc}, {}, {})",
                coerce_to_h(l, lt),
                coerce_to_h(r, rt)
            ),
            Ty::Handle,
        );
    }
    // Promote mixed Int/Float to Float.
    let (l, r, nt): (String, String, Ty) = match (lt, rt) {
        (Ty::Int, Ty::Float) => (format!("({l} as f64)"), r.to_string(), Ty::Float),
        (Ty::Float, Ty::Int) => (l.to_string(), format!("({r} as f64)"), Ty::Float),
        (t, _) => (l.to_string(), r.to_string(), t),
    };
    let (l, r) = (l.as_str(), r.as_str());
    match (op, nt) {
        (BinOp::Add, Ty::Int) => (format!("({l} + {r})"), Ty::Int),
        (BinOp::Sub, Ty::Int) => (format!("({l} - {r})"), Ty::Int),
        (BinOp::Mul, Ty::Int) => (format!("({l} * {r})"), Ty::Int),
        (BinOp::Div, Ty::Int) => (format!("(({l} as f64) / ({r} as f64))"), Ty::Float),
        (BinOp::FloorDiv, Ty::Int) => (format!("_tl_idiv({l}, {r})"), Ty::Int),
        (BinOp::Mod, Ty::Int) => (format!("_tl_imod({l}, {r})"), Ty::Int),
        (BinOp::BitAnd, Ty::Int) => (format!("({l} & {r})"), Ty::Int),
        (BinOp::BitOr, Ty::Int) => (format!("({l} | {r})"), Ty::Int),
        (BinOp::BitXor, Ty::Int) => (format!("({l} ^ {r})"), Ty::Int),
        (BinOp::LShift, Ty::Int) => (format!("({l} << {r})"), Ty::Int),
        (BinOp::RShift, Ty::Int) => (format!("({l} >> {r})"), Ty::Int),
        (BinOp::Add, Ty::Float) => (format!("({l} + {r})"), Ty::Float),
        (BinOp::Sub, Ty::Float) => (format!("({l} - {r})"), Ty::Float),
        (BinOp::Mul, Ty::Float) => (format!("({l} * {r})"), Ty::Float),
        (BinOp::Div, Ty::Float) => (format!("({l} / {r})"), Ty::Float),
        (BinOp::FloorDiv, Ty::Float) => (format!("(({l}) / ({r})).floor()"), Ty::Float),
        (BinOp::Mod, Ty::Float) => (format!("(({l}).rem_euclid({r}))"), Ty::Float),
        (BinOp::Pow, Ty::Float) => (format!("(({l}).powf({r}))"), Ty::Float),
        (BinOp::Eq, _) => (format!("({l} == {r})"), Ty::Bool),
        (BinOp::NotEq, _) => (format!("({l} != {r})"), Ty::Bool),
        (BinOp::Lt, _) => (format!("({l} < {r})"), Ty::Bool),
        (BinOp::LtEq, _) => (format!("({l} <= {r})"), Ty::Bool),
        (BinOp::Gt, _) => (format!("({l} > {r})"), Ty::Bool),
        (BinOp::GtEq, _) => (format!("({l} >= {r})"), Ty::Bool),
        _ => {
            let oc = binop_code(op);
            (
                format!(
                    "cb_binop({oc}, {}, {})",
                    coerce_to_h(l, nt),
                    coerce_to_h(r, nt)
                ),
                Ty::Handle,
            )
        }
    }
}

// ── Code generation context ───────────────────────────────────────────────────

/// コード生成コンテキスト: ローカル変数とモジュール内関数の追跡情報を保持する。
struct GenCtx<'a> {
    /// name → (is_mutable, storage_type)
    locals: HashMap<String, (bool, Ty)>,
    module_fns: &'a HashSet<String>,
    fn_sigs: &'a HashMap<String, FnSig>,
    counter: usize,
}

impl<'a> GenCtx<'a> {
    /// 新しいコンテキストを作成する。モジュール内関数名セットと関数シグネチャマップを受け取る。
    fn new(module_fns: &'a HashSet<String>, fn_sigs: &'a HashMap<String, FnSig>) -> Self {
        Self {
            locals: HashMap::new(),
            module_fns,
            fn_sigs,
            counter: 0,
        }
    }

    /// 一意な一時変数名を生成して返す。
    fn fresh(&mut self) -> String {
        let n = self.counter;
        self.counter += 1;
        format!("_t{n}")
    }

    /// ローカル変数を可変性と型情報付きで登録する。
    fn add_local(&mut self, name: &str, mutable: bool, ty: Ty) {
        self.locals.insert(name.to_string(), (mutable, ty));
    }

    /// 指定した名前がローカル変数として登録されているか確認する。
    fn is_local(&self, name: &str) -> bool {
        self.locals.contains_key(name)
    }

    /// 指定した名前がモジュール内関数として登録されているか確認する。
    fn is_module_fn(&self, name: &str) -> bool {
        self.module_fns.contains(name)
    }

    /// ローカル変数のストレージ型を返す。登録されていない場合は `Handle` を返す。
    fn local_type(&self, name: &str) -> Ty {
        self.locals.get(name).map(|(_, t)| *t).unwrap_or(Ty::Handle)
    }

    /// モジュール内関数の戻り値型を返す。シグネチャが未登録の場合は `Handle` を返す。
    fn fn_ret_type(&self, name: &str) -> Ty {
        self.fn_sigs.get(name).map(|s| s.ret).unwrap_or(Ty::Handle)
    }

    /// モジュール内関数のパラメータ可変性リストへの参照を返す。
    fn fn_param_mutabilities(&self, name: &str) -> Option<&Vec<bool>> {
        self.fn_sigs.get(name).map(|s| &s.param_mutabilities)
    }

    /// ローカル変数をコピーした子コンテキストを作成する（ネストしたスコープ用）。
    fn child(&self) -> GenCtx<'a> {
        GenCtx {
            locals: self.locals.clone(),
            module_fns: self.module_fns,
            fn_sigs: self.fn_sigs,
            counter: self.counter,
        }
    }
}

// ── Public entry point ────────────────────────────────────────────────────────

/// `stmts` 内のすべての適格な関数に対してRustソースファイルを生成する。
/// 少なくとも1つの適格な関数がある場合に `Some((rust_source, exports))` を返す。
pub fn generate_rust_module(stmts: &[Stmt]) -> Option<(String, Vec<FnExport>)> {
    struct EligibleFn<'a> {
        name: &'a str,
        params: &'a [Param],
        return_type: Option<&'a str>,
        body: &'a [Stmt],
    }

    let eligible: Vec<EligibleFn> = stmts
        .iter()
        .filter_map(|s| {
            if let Stmt::FnDef {
                name,
                template_params,
                params,
                body,
                is_abstract,
                return_type,
                ..
            } = s
            {
                if !template_params.is_empty() || *is_abstract {
                    return None;
                }
                if !body_eligible(body) {
                    return None;
                }
                Some(EligibleFn {
                    name,
                    params,
                    return_type: return_type.as_deref(),
                    body,
                })
            } else {
                None
            }
        })
        .collect();

    if eligible.is_empty() {
        return None;
    }

    // Only eligible functions have _impl generated; restrict intra-module routing to them.
    let module_fns: HashSet<String> = eligible.iter().map(|f| f.name.to_string()).collect();

    // Build fn_sigs: param storage types + return storage type for each eligible function.
    let fn_sigs: HashMap<String, FnSig> = eligible
        .iter()
        .map(|f| {
            let ret = ann_ty(f.return_type);
            let param_mutabilities = f.params.iter().map(|p| p.mutable).collect();
            (
                f.name.to_string(),
                FnSig {
                    ret,
                    param_mutabilities,
                },
            )
        })
        .collect();

    let mut out = String::new();
    out.push_str(MODULE_HEADER);

    for f in &eligible {
        let param_vars: Vec<String> = f.params.iter().map(|p| format!("_v_{}", p.name)).collect();

        out.push_str(&format!(
            "unsafe fn {}_impl({}) -> i64 {{\n",
            f.name,
            param_vars
                .iter()
                .map(|v| format!("mut {v}: i64"))
                .collect::<Vec<_>>()
                .join(", ")
        ));

        let mut ctx = GenCtx::new(&module_fns, &fn_sigs);
        for p in f.params {
            let pt = ann_ty(p.type_ann.as_deref());
            let mut_kw = if p.mutable { "mut " } else { "" };
            match pt {
                Ty::Int => out.push_str(&format!(
                    "    let {mut_kw}_v_{n}: i64 = cb_to_int(_v_{n});\n",
                    n = p.name
                )),
                Ty::Float => out.push_str(&format!(
                    "    let {mut_kw}_v_{n}: f64 = cb_to_float(_v_{n});\n",
                    n = p.name
                )),
                _ => {}
            }
            ctx.add_local(&p.name, p.mutable, pt);
        }

        gen_stmts(f.body, &mut ctx, 1, &mut out);

        out.push_str("    #[allow(unreachable_code)] TL_NONE\n");
        out.push_str("}\n\n");
    }

    let exports: Vec<FnExport> = eligible
        .iter()
        .map(|f| FnExport {
            name: f.name.to_string(),
            n_params: f.params.len(),
        })
        .collect();

    for exp in &exports {
        let name = &exp.name;
        let n = exp.n_params;
        out.push_str(&format!(
            "#[no_mangle]\npub unsafe extern \"C\" fn {name}_tl(args: *const i64, _n: i32) -> i64 {{\n"
        ));
        let arg_list: Vec<String> = (0..n).map(|i| format!("*args.add({i})")).collect();
        out.push_str(&format!("    {name}_impl({})\n", arg_list.join(", ")));
        out.push_str("}\n\n");
    }

    Some((out, exports))
}

// ── Eligibility ───────────────────────────────────────────────────────────────

/// 文のリストがすべてネイティブコンパイル適格かどうかを判定する。
fn body_eligible(stmts: &[Stmt]) -> bool {
    stmts.iter().all(|s| stmt_eligible(s))
}

/// 単一の文がネイティブコンパイル適格かどうかを判定する。
/// yield・クロージャ・例外処理・block_return・キーワード引数を含む文は非適格とする。
fn stmt_eligible(stmt: &Stmt) -> bool {
    match stmt {
        // Supported statements
        Stmt::Let(_, e) | Stmt::Mut(_, e) | Stmt::Const(_, e) => expr_eligible(e),
        Stmt::Assign { value, .. } | Stmt::CompoundAssign { value, .. } => expr_eligible(value),
        Stmt::AttrAssign { target, value } => expr_eligible(target) && expr_eligible(value),
        Stmt::AttrCompoundAssign { target, value, .. } => {
            expr_eligible(target) && expr_eligible(value)
        }
        Stmt::Return(Some(e)) => expr_eligible(e),
        Stmt::Return(None) => true,
        Stmt::Pass | Stmt::Break | Stmt::Continue => true,
        Stmt::Expr(e) => expr_eligible(e),
        Stmt::Freeze(_, _) => true, // no runtime effect in native code
        Stmt::Block(stmts) => body_eligible(stmts),
        Stmt::If {
            branches,
            else_body,
        } => {
            branches
                .iter()
                .all(|(cond, body)| expr_eligible(cond) && body_eligible(body))
                && else_body.as_ref().map_or(true, |b| body_eligible(b))
        }
        Stmt::While { cond, body } => expr_eligible(cond) && body_eligible(body),
        Stmt::For {
            targets,
            iter,
            body,
        } => targets.len() == 1 && expr_eligible(iter) && body_eligible(body),
        Stmt::Match { subject, arms, .. } => {
            expr_eligible(subject)
                && arms.iter().all(|arm| {
                    let pat_ok = match &arm.pattern {
                        MatchPattern::Case(e) => expr_eligible(e),
                        MatchPattern::IsType(_) => true,
                    };
                    pat_ok && body_eligible(&arm.body)
                })
        }
        // Ineligible
        Stmt::LetTuple { .. } => false, // not yet supported in native compilation
        Stmt::Yield(_) | Stmt::BlockReturn(_, _) | Stmt::LoopYield(_) => false,
        Stmt::FnDef { .. } | Stmt::GenDef { .. } => false, // closures
        Stmt::Try { .. } | Stmt::Raise { .. } => false,
        Stmt::Static(..) | Stmt::Import { .. } | Stmt::FromImport { .. } => false,
        Stmt::ClassDef { .. }
        | Stmt::TraitDef { .. }
        | Stmt::NewTypeDef { .. }
        | Stmt::EnumDef { .. } => false,
        Stmt::Field { .. } => false,
        Stmt::AsyncAssign { .. } => false,
        Stmt::BreakPoint { .. } | Stmt::DebugLet(..) => false,
    }
}

/// 単一の式がネイティブコンパイル適格かどうかを判定する。
/// スライス・セット・制御フロー式・キーワード引数は非適格とする。
fn expr_eligible(expr: &Expr) -> bool {
    match expr {
        // Literals: always OK
        Expr::Int(_) | Expr::Float(_) | Expr::Str(_) | Expr::Bool(_) | Expr::None => true,
        // Simple references
        Expr::Ident(_) => true,
        // Operators
        Expr::BinOp { left, right, .. } => expr_eligible(left) && expr_eligible(right),
        Expr::UnaryOp { operand, .. } => expr_eligible(operand),
        // Collection literals
        Expr::List(items) => items.iter().all(expr_eligible),
        Expr::Tuple(items) => items.iter().all(expr_eligible),
        Expr::Dict(pairs) => pairs
            .iter()
            .all(|(k, v)| expr_eligible(k) && expr_eligible(v)),
        // Calls: positional args only
        Expr::Call { func, args, .. } => {
            expr_eligible(func)
                && args.iter().all(|a| match a {
                    CallArg::Positional(e) => expr_eligible(e),
                    CallArg::Keyword { .. } => false, // keyword args unsupported
                })
        }
        // Attribute / subscript access
        Expr::Attr { object, .. } => expr_eligible(object),
        Expr::TraitAccess { object, .. } => expr_eligible(object),
        Expr::Subscript { object, index } => expr_eligible(object) && expr_eligible(index),
        Expr::Slice { .. } => false, // スライスはネイティブコンパイル非対応
        // Type check
        Expr::IsType { expr, .. } => expr_eligible(expr),
        // Template instantiation — treat the base as eligible
        Expr::TemplateInstantiate { base, .. } => expr_eligible(base),
        // Set literals: ineligible (no native set support)
        Expr::Set(_) => false,
        // Expression forms of control flow: ineligible
        Expr::Block { .. }
        | Expr::IfExpr { .. }
        | Expr::ForExpr { .. }
        | Expr::WhileExpr { .. }
        | Expr::MatchExpr { .. } => false,
        // Cast expressions: ineligible (runtime dispatch required)
        Expr::Cast { .. } => false,
        // Debug vars: ineligible (REPL only)
        Expr::DebugVar(_) => false,
    }
}

// ── Statement generation ──────────────────────────────────────────────────────

/// 文のリストに対してRustコードを生成し `out` に追記する。
fn gen_stmts(stmts: &[Stmt], ctx: &mut GenCtx, indent: usize, out: &mut String) {
    for stmt in stmts {
        gen_stmt(stmt, ctx, indent, out);
    }
}

/// 単一の文に対してRustコードを生成し `out` に追記する。
fn gen_stmt(stmt: &Stmt, ctx: &mut GenCtx, indent: usize, out: &mut String) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Let(name, expr) => {
            let (code, ty) = gen_typed_expr(expr, ctx);
            let st = store_ty(ty);
            ctx.add_local(name, false, st);
            match st {
                Ty::Int => out.push_str(&format!(
                    "{pad}let _v_{name}: i64 = {};\n",
                    coerce_to_i(&code, ty)
                )),
                Ty::Float => out.push_str(&format!(
                    "{pad}let _v_{name}: f64 = {};\n",
                    coerce_to_f(&code, ty)
                )),
                _ => out.push_str(&format!(
                    "{pad}let _v_{name}: i64 = {};\n",
                    coerce_to_h(&code, ty)
                )),
            }
        }
        Stmt::Const(name, expr) => {
            let (code, ty) = gen_typed_expr(expr, ctx);
            let st = store_ty(ty);
            ctx.add_local(name, false, st);
            match st {
                Ty::Int => out.push_str(&format!(
                    "{pad}let _v_{name}: i64 = {};\n",
                    coerce_to_i(&code, ty)
                )),
                Ty::Float => out.push_str(&format!(
                    "{pad}let _v_{name}: f64 = {};\n",
                    coerce_to_f(&code, ty)
                )),
                _ => out.push_str(&format!(
                    "{pad}let _v_{name}: i64 = {};\n",
                    coerce_to_h(&code, ty)
                )),
            }
        }
        Stmt::Mut(name, expr) => {
            let (code, ty) = gen_typed_expr(expr, ctx);
            let st = store_ty(ty);
            ctx.add_local(name, true, st);
            match st {
                Ty::Int => out.push_str(&format!(
                    "{pad}let mut _v_{name}: i64 = {};\n",
                    coerce_to_i(&code, ty)
                )),
                Ty::Float => out.push_str(&format!(
                    "{pad}let mut _v_{name}: f64 = {};\n",
                    coerce_to_f(&code, ty)
                )),
                _ => out.push_str(&format!(
                    "{pad}let mut _v_{name}: i64 = {};\n",
                    coerce_to_h(&code, ty)
                )),
            }
        }
        Stmt::Assign { name, value, .. } => {
            let (code, ty) = gen_typed_expr(value, ctx);
            let lt = ctx.local_type(name);
            let final_code = match lt {
                Ty::Int => coerce_to_i(&code, ty),
                Ty::Float => coerce_to_f(&code, ty),
                _ => coerce_to_h(&code, ty),
            };
            out.push_str(&format!("{pad}_v_{name} = {final_code};\n"));
        }
        Stmt::CompoundAssign {
            name, op, value, ..
        } => {
            let lt = ctx.local_type(name);
            let (rhs, rt) = gen_typed_expr(value, ctx);
            let lhs = format!("_v_{name}");
            let (result, result_ty) = specialize_binop(op, &lhs, lt, &rhs, rt);
            let final_code = match lt {
                Ty::Int => coerce_to_i(&result, result_ty),
                Ty::Float => coerce_to_f(&result, result_ty),
                _ => coerce_to_h(&result, result_ty),
            };
            out.push_str(&format!("{pad}_v_{name} = {final_code};\n"));
        }
        Stmt::AttrAssign { target, value } => {
            if let Expr::Attr { object, attr, .. } = target {
                let obj = gen_expr(object, ctx);
                let val = gen_expr(value, ctx);
                let attr_bytes = format!("b\"{}\"", attr);
                out.push_str(&format!("{pad}cb_set_attr({obj}, {attr_bytes}, {val});\n"));
            } else if let Expr::Subscript { object, index } = target {
                // Subscript assignment: use a callback for set_subscript
                // For now, generate a no-op comment (limited support)
                let obj = gen_expr(object, ctx);
                let key = gen_expr(index, ctx);
                let val = gen_expr(value, ctx);
                // Use get_attr on a fake setter — interpreter handles it via set_attr with key
                out.push_str(&format!("{pad}let _ = ({obj}, {key}, {val}); // subscript assign (interpreter fallback)\n"));
            } else {
                out.push_str(&format!("{pad}// AttrAssign: unsupported target form\n"));
            }
        }
        Stmt::AttrCompoundAssign { target, op, value } => {
            if let Expr::Attr { object, attr, .. } = target {
                let obj_expr = gen_expr(object, ctx);
                let tmp = ctx.fresh();
                let attr_bytes = format!("b\"{}\"", attr);
                let op_code = binop_code(op);
                let rhs = gen_expr(value, ctx);
                out.push_str(&format!("{pad}let {tmp}_obj: i64 = {obj_expr};\n"));
                out.push_str(&format!(
                    "{pad}let {tmp}_old: i64 = cb_get_attr({tmp}_obj, {attr_bytes});\n"
                ));
                out.push_str(&format!(
                    "{pad}let {tmp}_new: i64 = cb_binop({op_code}, {tmp}_old, {rhs});\n"
                ));
                out.push_str(&format!(
                    "{pad}cb_set_attr({tmp}_obj, {attr_bytes}, {tmp}_new);\n"
                ));
            }
        }
        Stmt::Return(Some(e)) => {
            let (code, ty) = gen_typed_expr(e, ctx);
            out.push_str(&format!("{pad}return {};\n", coerce_to_h(&code, ty)));
        }
        Stmt::Return(None) => {
            out.push_str(&format!("{pad}return TL_NONE;\n"));
        }
        Stmt::Pass => {
            out.push_str(&format!("{pad}// pass\n"));
        }
        Stmt::Break => {
            out.push_str(&format!("{pad}break;\n"));
        }
        Stmt::Continue => {
            out.push_str(&format!("{pad}continue;\n"));
        }
        Stmt::Expr(e) => {
            let expr = gen_expr(e, ctx);
            out.push_str(&format!("{pad}let _ = {expr};\n"));
        }
        Stmt::Freeze(name, _) => {
            // freeze is a runtime semantics operation; in native code the type system
            // already caught misuse, so no code needed.
            let _ = name;
        }
        Stmt::Block(stmts) => {
            out.push_str(&format!("{pad}{{\n"));
            let mut child = ctx.child();
            gen_stmts(stmts, &mut child, indent + 1, out);
            // propagate counter back
            ctx.counter = child.counter;
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::If {
            branches,
            else_body,
        } => {
            for (i, (cond, body)) in branches.iter().enumerate() {
                let (cond_code, cond_ty) = gen_typed_expr(cond, ctx);
                let cond_str = coerce_to_cond(&cond_code, cond_ty);
                if i == 0 {
                    out.push_str(&format!("{pad}if {cond_str} {{\n"));
                } else {
                    out.push_str(&format!("{pad}}} else if {cond_str} {{\n"));
                }
                let mut child = ctx.child();
                gen_stmts(body, &mut child, indent + 1, out);
                ctx.counter = child.counter;
            }
            if let Some(else_stmts) = else_body {
                out.push_str(&format!("{pad}}} else {{\n"));
                let mut child = ctx.child();
                gen_stmts(else_stmts, &mut child, indent + 1, out);
                ctx.counter = child.counter;
            }
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::While { cond, body } => {
            let (cond_code, cond_ty) = gen_typed_expr(cond, ctx);
            let cond_str = coerce_to_cond(&cond_code, cond_ty);
            out.push_str(&format!("{pad}while {cond_str} {{\n"));
            let mut child = ctx.child();
            gen_stmts(body, &mut child, indent + 1, out);
            ctx.counter = child.counter;
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::For {
            targets,
            iter,
            body,
        } => {
            // Tuple targets are ineligible and filtered by stmt_eligible; only single target here.
            let target = &targets[0];
            let iter_expr = gen_expr(iter, ctx);
            let tmp = ctx.fresh();
            out.push_str(&format!("{pad}{{\n"));
            out.push_str(&format!(
                "{pad}    let {tmp}_iter: i64 = cb_iter_from({iter_expr});\n"
            ));
            out.push_str(&format!("{pad}    loop {{\n"));
            out.push_str(&format!(
                "{pad}        let _v_{target}: i64 = cb_iter_next({tmp}_iter);\n"
            ));
            out.push_str(&format!(
                "{pad}        if _v_{target} == TL_STOP_ITER {{ break; }}\n"
            ));
            let mut child = ctx.child();
            child.add_local(target, false, Ty::Handle);
            gen_stmts(body, &mut child, indent + 2, out);
            ctx.counter = child.counter;
            out.push_str(&format!("{pad}    }}\n"));
            out.push_str(&format!("{pad}}}\n"));
        }
        Stmt::Match { subject, arms, .. } => {
            let subj_expr = gen_expr(subject, ctx);
            let tmp = ctx.fresh();
            out.push_str(&format!("{pad}let {tmp}_subj: i64 = {subj_expr};\n"));

            // Detect arm type: all Case or all IsType
            let has_value_case = arms
                .iter()
                .any(|a| matches!(a.pattern, MatchPattern::Case(_)));
            let has_is_type = arms
                .iter()
                .any(|a| matches!(a.pattern, MatchPattern::IsType(_)));

            let _ = has_value_case;
            let _ = has_is_type;

            for (i, arm) in arms.iter().enumerate() {
                let is_last = i == arms.len() - 1;

                match &arm.pattern {
                    MatchPattern::Case(Expr::Ident(w)) if w == "_" => {
                        // Wildcard
                        if i == 0 {
                            out.push_str(&format!("{pad}{{\n"));
                        } else {
                            out.push_str(&format!("{pad}}} else {{\n"));
                        }
                    }
                    MatchPattern::Case(pat_expr) => {
                        let pat = gen_expr(pat_expr, ctx);
                        let cond = format!("cb_is_truthy(cb_binop(OP_EQ, {tmp}_subj, {pat}))");
                        if i == 0 {
                            out.push_str(&format!("{pad}if {cond} {{\n"));
                        } else {
                            out.push_str(&format!("{pad}}} else if {cond} {{\n"));
                        }
                    }
                    MatchPattern::IsType(type_name) => {
                        let name_bytes = format!("b\"{}\"", type_name);
                        let cond = format!("cb_is_truthy(cb_is_type({tmp}_subj, {name_bytes}))");
                        if i == 0 {
                            out.push_str(&format!("{pad}if {cond} {{\n"));
                        } else {
                            out.push_str(&format!("{pad}}} else if {cond} {{\n"));
                        }
                    }
                }

                let mut child = ctx.child();
                gen_stmts(&arm.body, &mut child, indent + 1, out);
                ctx.counter = child.counter;

                if is_last {
                    out.push_str(&format!("{pad}}}\n"));
                }
            }
        }
        _ => {
            // Ineligible statements should have been filtered by body_eligible.
            out.push_str(&format!("{pad}// (ineligible statement omitted)\n"));
        }
    }
}

// ── Expression generation ─────────────────────────────────────────────────────

/// 式に対してネイティブ型付きのRust式を生成する。
/// `Int`/`Float` のローカル変数やリテラルは生の `i64`/`f64` を返し、それ以外は `i64` ハンドルを返す。
fn gen_typed_expr(expr: &Expr, ctx: &mut GenCtx) -> (String, Ty) {
    match expr {
        Expr::Int(n) => (format!("{n}i64"), Ty::Int),
        Expr::Float(f) => (format!("{f}f64"), Ty::Float),
        Expr::Bool(b) => (
            if *b {
                "TL_TRUE".to_string()
            } else {
                "TL_FALSE".to_string()
            },
            Ty::Handle,
        ),
        Expr::None => ("TL_NONE".to_string(), Ty::Handle),
        Expr::Str(s) => {
            let escaped = escape_bytes(s.as_bytes());
            (format!("cb_make_str(b\"{escaped}\")"), Ty::Handle)
        }
        Expr::Ident(name) => {
            if ctx.is_local(name) {
                let ty = ctx.local_type(name);
                (format!("_v_{name}"), ty)
            } else {
                let escaped = escape_bytes(name.as_bytes());
                (format!("cb_get_global(b\"{escaped}\")"), Ty::Handle)
            }
        }
        Expr::BinOp {
            op, left, right, ..
        } => {
            match op {
                BinOp::And => {
                    let tmp = ctx.fresh();
                    let lhs = gen_expr(left, ctx);
                    let rhs = gen_expr(right, ctx);
                    (format!("{{let {tmp} = {lhs}; if !cb_is_truthy({tmp}) {{{tmp}}} else {{{rhs}}}}}"), Ty::Handle)
                }
                BinOp::Or => {
                    let tmp = ctx.fresh();
                    let lhs = gen_expr(left, ctx);
                    let rhs = gen_expr(right, ctx);
                    (format!("{{let {tmp} = {lhs}; if cb_is_truthy({tmp}) {{{tmp}}} else {{{rhs}}}}}"), Ty::Handle)
                }
                _ => {
                    let (l, lt) = gen_typed_expr(left, ctx);
                    let (r, rt) = gen_typed_expr(right, ctx);
                    specialize_binop(op, &l, lt, &r, rt)
                }
            }
        }
        Expr::UnaryOp { op, operand } => {
            let op_code = unop_code(op);
            let o = gen_expr(operand, ctx);
            (format!("cb_unop({op_code}, {o})"), Ty::Handle)
        }
        Expr::Attr { object, attr, .. } => {
            let obj = gen_expr(object, ctx);
            let escaped = escape_bytes(attr.as_bytes());
            (format!("cb_get_attr({obj}, b\"{escaped}\")"), Ty::Handle)
        }
        Expr::TraitAccess {
            object,
            trait_name,
            attr,
        } => {
            let obj = gen_expr(object, ctx);
            let key = format!("{trait_name}::{attr}");
            let escaped = escape_bytes(key.as_bytes());
            (format!("cb_get_attr({obj}, b\"{escaped}\")"), Ty::Handle)
        }
        Expr::Subscript { object, index } => {
            let obj = gen_expr(object, ctx);
            let key = gen_expr(index, ctx);
            (format!("cb_subscript({obj}, {key})"), Ty::Handle)
        }
        Expr::IsType {
            expr,
            negated,
            type_name,
            ..
        } => {
            let obj = gen_expr(expr, ctx);
            let escaped = escape_bytes(type_name.as_bytes());
            let type_h = format!("cb_is_type({obj}, b\"{escaped}\")");
            if *negated {
                (
                    format!("(if {type_h} == TL_TRUE {{ TL_FALSE }} else {{ TL_TRUE }})"),
                    Ty::Handle,
                )
            } else {
                (type_h, Ty::Handle)
            }
        }
        Expr::Call { func, args, .. } => {
            // For typed intra-module calls, unwrap the returned handle to a raw native value.
            if let Expr::Ident(name) = func.as_ref() {
                if ctx.is_module_fn(name) && !ctx.is_local(name) {
                    let ret = ctx.fn_ret_type(name);
                    if ret != Ty::Handle {
                        let call_h = gen_call(func, args, ctx);
                        return match ret {
                            Ty::Int => (format!("cb_to_int({call_h})"), Ty::Int),
                            Ty::Float => (format!("cb_to_float({call_h})"), Ty::Float),
                            _ => unreachable!(),
                        };
                    }
                }
            }
            (gen_call(func, args, ctx), Ty::Handle)
        }
        Expr::List(items) => {
            if items.is_empty() {
                ("cb_make_list(&[])".to_string(), Ty::Handle)
            } else {
                let exprs: Vec<String> = items.iter().map(|e| gen_expr(e, ctx)).collect();
                (format!("cb_make_list(&[{}])", exprs.join(", ")), Ty::Handle)
            }
        }
        Expr::Tuple(items) => {
            if items.is_empty() {
                ("cb_make_tuple(&[])".to_string(), Ty::Handle)
            } else {
                let exprs: Vec<String> = items.iter().map(|e| gen_expr(e, ctx)).collect();
                (
                    format!("cb_make_tuple(&[{}])", exprs.join(", ")),
                    Ty::Handle,
                )
            }
        }
        Expr::Dict(pairs) => {
            if pairs.is_empty() {
                ("cb_make_dict(&[], &[])".to_string(), Ty::Handle)
            } else {
                let ks: Vec<String> = pairs.iter().map(|(k, _)| gen_expr(k, ctx)).collect();
                let vs: Vec<String> = pairs.iter().map(|(_, v)| gen_expr(v, ctx)).collect();
                (
                    format!("cb_make_dict(&[{}], &[{}])", ks.join(", "), vs.join(", ")),
                    Ty::Handle,
                )
            }
        }
        Expr::TemplateInstantiate { base, .. } => (gen_expr(base, ctx), Ty::Handle),
        _ => ("TL_NONE /* unsupported expr */".to_string(), Ty::Handle),
    }
}

/// ハンドル型 (`i64`) のRust式を生成して返す。
fn gen_expr(expr: &Expr, ctx: &mut GenCtx) -> String {
    let (code, ty) = gen_typed_expr(expr, ctx);
    coerce_to_h(&code, ty)
}

/// 関数呼び出しのRustコードを生成する。
/// モジュール内直接呼び出しの場合はアリーナ保存・コンパクション付きの直接呼び出しを生成し、
/// それ以外は `cb_call` を通じたハンドル呼び出しを生成する。
fn gen_call(func: &Expr, args: &[CallArg], ctx: &mut GenCtx) -> String {
    // Collect positional arg expressions (keyword args were filtered by expr_eligible)
    let arg_exprs: Vec<String> = args.iter().map(|a| gen_expr(a.expr(), ctx)).collect();

    // Intra-module direct call: `name` in module_fns and not shadowed by a local.
    // Immutable (`let`) parameters are wrapped with cb_deep_copy so the callee
    // cannot mutate the caller's reference-type values.
    if let Expr::Ident(name) = func {
        if ctx.is_module_fn(name) && !ctx.is_local(name) {
            let mutabilities = ctx.fn_param_mutabilities(name);
            let wrapped: Vec<String> = arg_exprs
                .iter()
                .enumerate()
                .map(|(i, expr)| {
                    let is_mut = mutabilities.and_then(|m| m.get(i)).copied().unwrap_or(true);
                    if is_mut {
                        expr.clone()
                    } else {
                        format!("cb_deep_copy({expr})")
                    }
                })
                .collect();
            let args_str = wrapped.join(", ");
            return format!(
                "{{let _s=cb_arena_save();let _r={name}_impl({args_str});cb_arena_compact(_r,_s)}}"
            );
        }
    }

    // All other calls: get function handle, then call_fn
    let fn_h = gen_expr(func, ctx);
    if arg_exprs.is_empty() {
        format!("cb_call({fn_h}, &[])")
    } else {
        format!("cb_call({fn_h}, &[{}])", arg_exprs.join(", "))
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// 二項演算子を対応する整数コードに変換する。
fn binop_code(op: &BinOp) -> i32 {
    match op {
        BinOp::Add => 0,
        BinOp::Sub => 1,
        BinOp::Mul => 2,
        BinOp::Div => 3,
        BinOp::FloorDiv => 4,
        BinOp::Mod => 5,
        BinOp::Pow => 6,
        BinOp::Eq => 7,
        BinOp::NotEq => 8,
        BinOp::Lt => 9,
        BinOp::LtEq => 10,
        BinOp::Gt => 11,
        BinOp::GtEq => 12,
        BinOp::BitAnd => 13,
        BinOp::BitOr => 14,
        BinOp::BitXor => 15,
        BinOp::LShift => 16,
        BinOp::RShift => 17,
        BinOp::In => 18,
        BinOp::NotIn => 19,
        BinOp::And | BinOp::Or => unreachable!("and/or handled separately"),
    }
}

/// 単項演算子を対応する整数コードに変換する。
fn unop_code(op: &UnaryOp) -> i32 {
    match op {
        UnaryOp::Neg => 0,
        UnaryOp::Not => 1,
        UnaryOp::BitNot => 2,
    }
}

/// バイト列をRustの `b"..."` バイト文字列リテラル内で使用可能な形式にエスケープする。
fn escape_bytes(bytes: &[u8]) -> String {
    let mut out = String::new();
    for &b in bytes {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            _ => out.push_str(&format!("\\x{b:02x}")),
        }
    }
    out
}
