; Auto-generated by Havakyrie compiler — do not edit.

; HvCallbacks: 37 function-pointer fields (opaque ptr, LLVM 15+)
%HvCallbacks = type { ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr }

@CB = internal global ptr null

define dllexport void @hv_init(ptr %cb) {
  store ptr %cb, ptr @CB
  ret void
}

; Python-compatible floor division for i64
define internal i64 @_tl_idiv(i64 %a, i64 %b) {
  %d    = sdiv i64 %a, %b
  %r    = srem i64 %a, %b
  %rnz  = icmp ne i64 %r, 0
  %rneg = icmp slt i64 %r, 0
  %bneg = icmp slt i64 %b, 0
  %diff = xor i1 %rneg, %bneg
  %need = and i1 %rnz, %diff
  %dadj = sub i64 %d, 1
  %res  = select i1 %need, i64 %dadj, i64 %d
  ret i64 %res
}

; Python-compatible modulo for i64
define internal i64 @_tl_imod(i64 %a, i64 %b) {
  %r    = srem i64 %a, %b
  %rnz  = icmp ne i64 %r, 0
  %rneg = icmp slt i64 %r, 0
  %bneg = icmp slt i64 %b, 0
  %diff = xor i1 %rneg, %bneg
  %need = and i1 %rnz, %diff
  %radj = add i64 %r, %b
  %res  = select i1 %need, i64 %radj, i64 %r
  ret i64 %res
}

declare double @llvm.pow.f64(double, double)
declare double @llvm.floor.f64(double)

@_s0 = private unnamed_addr constant [2 x i8] c"x\00", align 1
@_s1 = private unnamed_addr constant [2 x i8] c"y\00", align 1
@_s2 = private unnamed_addr constant [2 x i8] c"z\00", align 1
@_s3 = private unnamed_addr constant [5 x i8] c"mass\00", align 1

define internal i64 @Particle____init___impl(i64 %_h0, i64 %_h1, i64 %_h2, i64 %_h3, i64 %_h4) {
entry:
  %_al_self = alloca i64, align 8
  %_al_x = alloca double, align 8
  %_al_y = alloca double, align 8
  %_al_z = alloca double, align 8
  %_al_mass = alloca double, align 8
  store i64 %_h0, ptr %_al_self
  %_r0 = load ptr, ptr @CB
  %_r1 = getelementptr inbounds %HvCallbacks, ptr %_r0, i32 0, i32 23
  %_r2 = load ptr, ptr %_r1
  %_r3 = call double (i64) %_r2(i64 %_h1)
  store double %_r3, ptr %_al_x
  %_r4 = load ptr, ptr @CB
  %_r5 = getelementptr inbounds %HvCallbacks, ptr %_r4, i32 0, i32 23
  %_r6 = load ptr, ptr %_r5
  %_r7 = call double (i64) %_r6(i64 %_h2)
  store double %_r7, ptr %_al_y
  %_r8 = load ptr, ptr @CB
  %_r9 = getelementptr inbounds %HvCallbacks, ptr %_r8, i32 0, i32 23
  %_r10 = load ptr, ptr %_r9
  %_r11 = call double (i64) %_r10(i64 %_h3)
  store double %_r11, ptr %_al_z
  %_r12 = load ptr, ptr @CB
  %_r13 = getelementptr inbounds %HvCallbacks, ptr %_r12, i32 0, i32 23
  %_r14 = load ptr, ptr %_r13
  %_r15 = call double (i64) %_r14(i64 %_h4)
  store double %_r15, ptr %_al_mass
  %_r16 = load i64, ptr %_al_self
  %_r17 = load double, ptr %_al_x
  %_r18 = load ptr, ptr @CB
  %_r19 = getelementptr inbounds %HvCallbacks, ptr %_r18, i32 0, i32 1
  %_r20 = load ptr, ptr %_r19
  %_r21 = call i64 (double) %_r20(double %_r17)
  %_r22 = load ptr, ptr @CB
  %_r23 = getelementptr inbounds %HvCallbacks, ptr %_r22, i32 0, i32 13
  %_r24 = load ptr, ptr %_r23
  call void (i64, ptr, i32, i64) %_r24(i64 %_r16, ptr @_s0, i32 1, i64 %_r21)
  %_r25 = load i64, ptr %_al_self
  %_r26 = load double, ptr %_al_y
  %_r27 = load ptr, ptr @CB
  %_r28 = getelementptr inbounds %HvCallbacks, ptr %_r27, i32 0, i32 1
  %_r29 = load ptr, ptr %_r28
  %_r30 = call i64 (double) %_r29(double %_r26)
  %_r31 = load ptr, ptr @CB
  %_r32 = getelementptr inbounds %HvCallbacks, ptr %_r31, i32 0, i32 13
  %_r33 = load ptr, ptr %_r32
  call void (i64, ptr, i32, i64) %_r33(i64 %_r25, ptr @_s1, i32 1, i64 %_r30)
  %_r34 = load i64, ptr %_al_self
  %_r35 = load double, ptr %_al_z
  %_r36 = load ptr, ptr @CB
  %_r37 = getelementptr inbounds %HvCallbacks, ptr %_r36, i32 0, i32 1
  %_r38 = load ptr, ptr %_r37
  %_r39 = call i64 (double) %_r38(double %_r35)
  %_r40 = load ptr, ptr @CB
  %_r41 = getelementptr inbounds %HvCallbacks, ptr %_r40, i32 0, i32 13
  %_r42 = load ptr, ptr %_r41
  call void (i64, ptr, i32, i64) %_r42(i64 %_r34, ptr @_s2, i32 1, i64 %_r39)
  %_r43 = load i64, ptr %_al_self
  %_r44 = load double, ptr %_al_mass
  %_r45 = load ptr, ptr @CB
  %_r46 = getelementptr inbounds %HvCallbacks, ptr %_r45, i32 0, i32 1
  %_r47 = load ptr, ptr %_r46
  %_r48 = call i64 (double) %_r47(double %_r44)
  %_r49 = load ptr, ptr @CB
  %_r50 = getelementptr inbounds %HvCallbacks, ptr %_r49, i32 0, i32 13
  %_r51 = load ptr, ptr %_r50
  call void (i64, ptr, i32, i64) %_r51(i64 %_r43, ptr @_s3, i32 4, i64 %_r48)
  ret i64 0
}

define dllexport i64 @Particle____init___tl(ptr %args, i32 %_n) {
  %_a0 = getelementptr inbounds i64, ptr %args, i32 0
  %_v0 = load i64, ptr %_a0
  %_a1 = getelementptr inbounds i64, ptr %args, i32 1
  %_v1 = load i64, ptr %_a1
  %_a2 = getelementptr inbounds i64, ptr %args, i32 2
  %_v2 = load i64, ptr %_a2
  %_a3 = getelementptr inbounds i64, ptr %args, i32 3
  %_v3 = load i64, ptr %_a3
  %_a4 = getelementptr inbounds i64, ptr %args, i32 4
  %_v4 = load i64, ptr %_a4
  %_res = call i64 @Particle____init___impl(i64 %_v0, i64 %_v1, i64 %_v2, i64 %_v3, i64 %_v4)
  ret i64 %_res
}

define internal double @compute_mut_impl(i64 %_h0) {
entry:
  %_al_pts = alloca i64, align 8
  %_al_total = alloca double, align 8
  %_iter5 = alloca i64, align 8
  %_al_p = alloca i64, align 8
  %_al_d2 = alloca i64, align 8
  store i64 %_h0, ptr %_al_pts
  store double 0.0, ptr %_al_total
  %_r0 = load i64, ptr %_al_pts
  %_r1 = load ptr, ptr @CB
  %_r2 = getelementptr inbounds %HvCallbacks, ptr %_r1, i32 0, i32 16
  %_r3 = load ptr, ptr %_r2
  %_r4 = call i64 (i64) %_r3(i64 %_r0)
  store i64 %_r4, ptr %_iter5
  br label %_bb1

_bb1:
  %_r6 = load i64, ptr %_iter5
  %_r7 = load ptr, ptr @CB
  %_r8 = getelementptr inbounds %HvCallbacks, ptr %_r7, i32 0, i32 17
  %_r9 = load ptr, ptr %_r8
  %_r10 = call i64 (i64) %_r9(i64 %_r6)
  store i64 %_r10, ptr %_al_p
  %_r11 = icmp eq i64 %_r10, -1
  br i1 %_r11, label %_bb0, label %_bb2

_bb2:
  %_r12 = load i64, ptr %_al_p
  %_r13 = load ptr, ptr @CB
  %_r14 = getelementptr inbounds %HvCallbacks, ptr %_r13, i32 0, i32 12
  %_r15 = load ptr, ptr %_r14
  %_r16 = call i64 (i64, ptr, i32) %_r15(i64 %_r12, ptr @_s0, i32 1)
  %_r17 = load i64, ptr %_al_p
  %_r18 = load ptr, ptr @CB
  %_r19 = getelementptr inbounds %HvCallbacks, ptr %_r18, i32 0, i32 12
  %_r20 = load ptr, ptr %_r19
  %_r21 = call i64 (i64, ptr, i32) %_r20(i64 %_r17, ptr @_s0, i32 1)
  %_r22 = load ptr, ptr @CB
  %_r23 = getelementptr inbounds %HvCallbacks, ptr %_r22, i32 0, i32 9
  %_r24 = load ptr, ptr %_r23
  %_r25 = call i64 (i32, i64, i64) %_r24(i32 2, i64 %_r16, i64 %_r21)
  %_r26 = load i64, ptr %_al_p
  %_r27 = load ptr, ptr @CB
  %_r28 = getelementptr inbounds %HvCallbacks, ptr %_r27, i32 0, i32 12
  %_r29 = load ptr, ptr %_r28
  %_r30 = call i64 (i64, ptr, i32) %_r29(i64 %_r26, ptr @_s1, i32 1)
  %_r31 = load i64, ptr %_al_p
  %_r32 = load ptr, ptr @CB
  %_r33 = getelementptr inbounds %HvCallbacks, ptr %_r32, i32 0, i32 12
  %_r34 = load ptr, ptr %_r33
  %_r35 = call i64 (i64, ptr, i32) %_r34(i64 %_r31, ptr @_s1, i32 1)
  %_r36 = load ptr, ptr @CB
  %_r37 = getelementptr inbounds %HvCallbacks, ptr %_r36, i32 0, i32 9
  %_r38 = load ptr, ptr %_r37
  %_r39 = call i64 (i32, i64, i64) %_r38(i32 2, i64 %_r30, i64 %_r35)
  %_r40 = load ptr, ptr @CB
  %_r41 = getelementptr inbounds %HvCallbacks, ptr %_r40, i32 0, i32 9
  %_r42 = load ptr, ptr %_r41
  %_r43 = call i64 (i32, i64, i64) %_r42(i32 0, i64 %_r25, i64 %_r39)
  %_r44 = load i64, ptr %_al_p
  %_r45 = load ptr, ptr @CB
  %_r46 = getelementptr inbounds %HvCallbacks, ptr %_r45, i32 0, i32 12
  %_r47 = load ptr, ptr %_r46
  %_r48 = call i64 (i64, ptr, i32) %_r47(i64 %_r44, ptr @_s2, i32 1)
  %_r49 = load i64, ptr %_al_p
  %_r50 = load ptr, ptr @CB
  %_r51 = getelementptr inbounds %HvCallbacks, ptr %_r50, i32 0, i32 12
  %_r52 = load ptr, ptr %_r51
  %_r53 = call i64 (i64, ptr, i32) %_r52(i64 %_r49, ptr @_s2, i32 1)
  %_r54 = load ptr, ptr @CB
  %_r55 = getelementptr inbounds %HvCallbacks, ptr %_r54, i32 0, i32 9
  %_r56 = load ptr, ptr %_r55
  %_r57 = call i64 (i32, i64, i64) %_r56(i32 2, i64 %_r48, i64 %_r53)
  %_r58 = load ptr, ptr @CB
  %_r59 = getelementptr inbounds %HvCallbacks, ptr %_r58, i32 0, i32 9
  %_r60 = load ptr, ptr %_r59
  %_r61 = call i64 (i32, i64, i64) %_r60(i32 0, i64 %_r43, i64 %_r57)
  store i64 %_r61, ptr %_al_d2
  %_r62 = load double, ptr %_al_total
  %_r63 = load i64, ptr %_al_p
  %_r64 = load ptr, ptr @CB
  %_r65 = getelementptr inbounds %HvCallbacks, ptr %_r64, i32 0, i32 12
  %_r66 = load ptr, ptr %_r65
  %_r67 = call i64 (i64, ptr, i32) %_r66(i64 %_r63, ptr @_s3, i32 4)
  %_r68 = load i64, ptr %_al_d2
  %_r69 = load ptr, ptr @CB
  %_r70 = getelementptr inbounds %HvCallbacks, ptr %_r69, i32 0, i32 9
  %_r71 = load ptr, ptr %_r70
  %_r72 = call i64 (i32, i64, i64) %_r71(i32 2, i64 %_r67, i64 %_r68)
  %_r73 = load ptr, ptr @CB
  %_r74 = getelementptr inbounds %HvCallbacks, ptr %_r73, i32 0, i32 1
  %_r75 = load ptr, ptr %_r74
  %_r76 = call i64 (double) %_r75(double %_r62)
  %_r77 = load ptr, ptr @CB
  %_r78 = getelementptr inbounds %HvCallbacks, ptr %_r77, i32 0, i32 9
  %_r79 = load ptr, ptr %_r78
  %_r80 = call i64 (i32, i64, i64) %_r79(i32 0, i64 %_r76, i64 %_r72)
  %_r81 = load ptr, ptr @CB
  %_r82 = getelementptr inbounds %HvCallbacks, ptr %_r81, i32 0, i32 23
  %_r83 = load ptr, ptr %_r82
  %_r84 = call double (i64) %_r83(i64 %_r80)
  store double %_r84, ptr %_al_total
  br label %_bb1

_bb0:
  %_r85 = load double, ptr %_al_total
  ret double %_r85
}

define dllexport i64 @compute_mut_tl(ptr %args, i32 %_n) {
  %_a0 = getelementptr inbounds i64, ptr %args, i32 0
  %_v0 = load i64, ptr %_a0
  %_raw = call double @compute_mut_impl(i64 %_v0)
  %_cb_tl = load ptr, ptr @CB
  %_mf_p = getelementptr inbounds %HvCallbacks, ptr %_cb_tl, i32 0, i32 1
  %_mf = load ptr, ptr %_mf_p
  %_res = call i64 (double) %_mf(double %_raw)
  ret i64 %_res
}

define internal double @compute_frozen_impl(i64 %_h0) {
entry:
  %_al_pts = alloca i64, align 8
  %_al_total = alloca double, align 8
  %_iter5 = alloca i64, align 8
  %_al_p = alloca i64, align 8
  %_al_d2 = alloca i64, align 8
  store i64 %_h0, ptr %_al_pts
  store double 0.0, ptr %_al_total
  %_r0 = load i64, ptr %_al_pts
  %_r1 = load ptr, ptr @CB
  %_r2 = getelementptr inbounds %HvCallbacks, ptr %_r1, i32 0, i32 16
  %_r3 = load ptr, ptr %_r2
  %_r4 = call i64 (i64) %_r3(i64 %_r0)
  store i64 %_r4, ptr %_iter5
  br label %_bb1

_bb1:
  %_r6 = load i64, ptr %_iter5
  %_r7 = load ptr, ptr @CB
  %_r8 = getelementptr inbounds %HvCallbacks, ptr %_r7, i32 0, i32 17
  %_r9 = load ptr, ptr %_r8
  %_r10 = call i64 (i64) %_r9(i64 %_r6)
  store i64 %_r10, ptr %_al_p
  %_r11 = icmp eq i64 %_r10, -1
  br i1 %_r11, label %_bb0, label %_bb2

_bb2:
  %_r12 = load i64, ptr %_al_p
  %_r13 = load ptr, ptr @CB
  %_r14 = getelementptr inbounds %HvCallbacks, ptr %_r13, i32 0, i32 12
  %_r15 = load ptr, ptr %_r14
  %_r16 = call i64 (i64, ptr, i32) %_r15(i64 %_r12, ptr @_s0, i32 1)
  %_r17 = load i64, ptr %_al_p
  %_r18 = load ptr, ptr @CB
  %_r19 = getelementptr inbounds %HvCallbacks, ptr %_r18, i32 0, i32 12
  %_r20 = load ptr, ptr %_r19
  %_r21 = call i64 (i64, ptr, i32) %_r20(i64 %_r17, ptr @_s0, i32 1)
  %_r22 = load ptr, ptr @CB
  %_r23 = getelementptr inbounds %HvCallbacks, ptr %_r22, i32 0, i32 9
  %_r24 = load ptr, ptr %_r23
  %_r25 = call i64 (i32, i64, i64) %_r24(i32 2, i64 %_r16, i64 %_r21)
  %_r26 = load i64, ptr %_al_p
  %_r27 = load ptr, ptr @CB
  %_r28 = getelementptr inbounds %HvCallbacks, ptr %_r27, i32 0, i32 12
  %_r29 = load ptr, ptr %_r28
  %_r30 = call i64 (i64, ptr, i32) %_r29(i64 %_r26, ptr @_s1, i32 1)
  %_r31 = load i64, ptr %_al_p
  %_r32 = load ptr, ptr @CB
  %_r33 = getelementptr inbounds %HvCallbacks, ptr %_r32, i32 0, i32 12
  %_r34 = load ptr, ptr %_r33
  %_r35 = call i64 (i64, ptr, i32) %_r34(i64 %_r31, ptr @_s1, i32 1)
  %_r36 = load ptr, ptr @CB
  %_r37 = getelementptr inbounds %HvCallbacks, ptr %_r36, i32 0, i32 9
  %_r38 = load ptr, ptr %_r37
  %_r39 = call i64 (i32, i64, i64) %_r38(i32 2, i64 %_r30, i64 %_r35)
  %_r40 = load ptr, ptr @CB
  %_r41 = getelementptr inbounds %HvCallbacks, ptr %_r40, i32 0, i32 9
  %_r42 = load ptr, ptr %_r41
  %_r43 = call i64 (i32, i64, i64) %_r42(i32 0, i64 %_r25, i64 %_r39)
  %_r44 = load i64, ptr %_al_p
  %_r45 = load ptr, ptr @CB
  %_r46 = getelementptr inbounds %HvCallbacks, ptr %_r45, i32 0, i32 12
  %_r47 = load ptr, ptr %_r46
  %_r48 = call i64 (i64, ptr, i32) %_r47(i64 %_r44, ptr @_s2, i32 1)
  %_r49 = load i64, ptr %_al_p
  %_r50 = load ptr, ptr @CB
  %_r51 = getelementptr inbounds %HvCallbacks, ptr %_r50, i32 0, i32 12
  %_r52 = load ptr, ptr %_r51
  %_r53 = call i64 (i64, ptr, i32) %_r52(i64 %_r49, ptr @_s2, i32 1)
  %_r54 = load ptr, ptr @CB
  %_r55 = getelementptr inbounds %HvCallbacks, ptr %_r54, i32 0, i32 9
  %_r56 = load ptr, ptr %_r55
  %_r57 = call i64 (i32, i64, i64) %_r56(i32 2, i64 %_r48, i64 %_r53)
  %_r58 = load ptr, ptr @CB
  %_r59 = getelementptr inbounds %HvCallbacks, ptr %_r58, i32 0, i32 9
  %_r60 = load ptr, ptr %_r59
  %_r61 = call i64 (i32, i64, i64) %_r60(i32 0, i64 %_r43, i64 %_r57)
  store i64 %_r61, ptr %_al_d2
  %_r62 = load double, ptr %_al_total
  %_r63 = load i64, ptr %_al_p
  %_r64 = load ptr, ptr @CB
  %_r65 = getelementptr inbounds %HvCallbacks, ptr %_r64, i32 0, i32 12
  %_r66 = load ptr, ptr %_r65
  %_r67 = call i64 (i64, ptr, i32) %_r66(i64 %_r63, ptr @_s3, i32 4)
  %_r68 = load i64, ptr %_al_d2
  %_r69 = load ptr, ptr @CB
  %_r70 = getelementptr inbounds %HvCallbacks, ptr %_r69, i32 0, i32 9
  %_r71 = load ptr, ptr %_r70
  %_r72 = call i64 (i32, i64, i64) %_r71(i32 2, i64 %_r67, i64 %_r68)
  %_r73 = load ptr, ptr @CB
  %_r74 = getelementptr inbounds %HvCallbacks, ptr %_r73, i32 0, i32 1
  %_r75 = load ptr, ptr %_r74
  %_r76 = call i64 (double) %_r75(double %_r62)
  %_r77 = load ptr, ptr @CB
  %_r78 = getelementptr inbounds %HvCallbacks, ptr %_r77, i32 0, i32 9
  %_r79 = load ptr, ptr %_r78
  %_r80 = call i64 (i32, i64, i64) %_r79(i32 0, i64 %_r76, i64 %_r72)
  %_r81 = load ptr, ptr @CB
  %_r82 = getelementptr inbounds %HvCallbacks, ptr %_r81, i32 0, i32 23
  %_r83 = load ptr, ptr %_r82
  %_r84 = call double (i64) %_r83(i64 %_r80)
  store double %_r84, ptr %_al_total
  br label %_bb1

_bb0:
  %_r85 = load double, ptr %_al_total
  ret double %_r85
}

define dllexport i64 @compute_frozen_tl(ptr %args, i32 %_n) {
  %_a0 = getelementptr inbounds i64, ptr %args, i32 0
  %_v0 = load i64, ptr %_a0
  %_raw = call double @compute_frozen_impl(i64 %_v0)
  %_cb_tl = load ptr, ptr @CB
  %_mf_p = getelementptr inbounds %HvCallbacks, ptr %_cb_tl, i32 0, i32 1
  %_mf = load ptr, ptr %_mf_p
  %_res = call i64 (double) %_mf(double %_raw)
  ret i64 %_res
}
