# math.pyi — Arrow 同梱の型スタブ（BYTECODE_VM_PLAN #19 / 本計画 群6）。
#
# `math` も C 組み込みで `.py` が無い（`time.pyi` の注記と同じ事情）。
#
# ⚠ 関数だけを書く。`math.pi` / `math.e` のようなモジュール定数は
#   `extract_py_type_stubs` が `def` / `class` しか見ず、`convert_python_source` も
#   値なしの `x: float` を捨てるため拾えない（群6 S3 の積み残し）。

def sqrt(x: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def exp(x: float) -> float: ...
def log(x: float) -> float: ...
def log2(x: float) -> float: ...
def log10(x: float) -> float: ...
def floor(x: float) -> int: ...
def ceil(x: float) -> int: ...
def trunc(x: float) -> int: ...
def fabs(x: float) -> float: ...
def fmod(x: float, y: float) -> float: ...
def copysign(x: float, y: float) -> float: ...
def sin(x: float) -> float: ...
def cos(x: float) -> float: ...
def tan(x: float) -> float: ...
def asin(x: float) -> float: ...
def acos(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...
def hypot(x: float, y: float) -> float: ...
def degrees(x: float) -> float: ...
def radians(x: float) -> float: ...
def isnan(x: float) -> bool: ...
def isinf(x: float) -> bool: ...
def isfinite(x: float) -> bool: ...
def gcd(a: int, b: int) -> int: ...
def factorial(n: int) -> int: ...
