# time.pyi — Arrow 同梱の型スタブ（BYTECODE_VM_PLAN #19 / 本計画 群6）。
#
# `time` は CPython の**C 組み込みモジュール**で `.py` が存在しない。そのため
# `Parser::python_search_dirs()` が stdlib まで辿っても必ず空振りし、
# `import[py-int] time` の戻り値型は**恒久的に検査されない**状態だった。
#
# ⚠ ここに書けるのは `py_type_to_arrow` が解釈できる型だけ（int / float / str /
#   bool / None / bytes / list[T] / set[T] / Optional[T] / `X | None`）。
#   dict[K,V] と tuple[A,B] は要素型が落ちる。
# ⚠ **モジュール定数は現状どちらの経路も拾わない**ので関数だけを書く（群6 S3）。

def time() -> float: ...
def time_ns() -> int: ...
def monotonic() -> float: ...
def monotonic_ns() -> int: ...
def perf_counter() -> float: ...
def perf_counter_ns() -> int: ...
def process_time() -> float: ...
def sleep(secs: float) -> None: ...
