export type LangType = string;

export type BuiltinMethodInfo = { ret: LangType; sig: string };

// Used by both analysis.ts (collectFuncDefs) and native_module.ts (parseTlStub).
// RetType can be complex: function[T]->R, function{name:T}->R, etc.
export const FUNC_DEF_RE = /^(\s*)(fn|gen)\s+([A-Za-z_]\w*)(?:\[[^\]]*\])?\s*\(([^)]*)\)\s*(?:->\s*(.+?))?\s*:\s*$/;

export const BUILTIN_RETURN_TYPES: Record<string, LangType> = {
    print: 'None', exec: 'None',
    len: 'int', id: 'int', hash: 'int', ord: 'int', round: 'int',
    chr: 'str', hex: 'str', oct: 'str', bin: 'str', repr: 'str', input: 'str', format: 'str',
    int: 'int', uint: 'uint', float: 'float', str: 'str', bool: 'bool',
    isinstance: 'bool', issubclass: 'bool', callable: 'bool', hasattr: 'bool',
    abs: 'unknown', max: 'unknown', min: 'unknown', sum: 'unknown',
    range: 'unknown', enumerate: 'unknown', zip: 'unknown', map: 'unknown', filter: 'unknown',
    sorted: 'unknown', reversed: 'unknown', getattr: 'unknown', next: 'unknown',
    iter: 'unknown', open: 'unknown', eval: 'unknown', globals: 'unknown',
    locals: 'unknown', vars: 'unknown', dir: 'unknown', super: 'unknown', type: 'unknown',
};

export const BUILTIN_TYPE_METHODS: Readonly<Record<string, Readonly<Record<string, BuiltinMethodInfo>>>> = {
    str: {
        upper:        { ret: 'str',                  sig: 'fn upper() -> str' },
        lower:        { ret: 'str',                  sig: 'fn lower() -> str' },
        swapcase:     { ret: 'str',                  sig: 'fn swapcase() -> str' },
        capitalize:   { ret: 'str',                  sig: 'fn capitalize() -> str' },
        title:        { ret: 'str',                  sig: 'fn title() -> str' },
        strip:        { ret: 'str',                  sig: 'fn strip(chars: str = None) -> str' },
        lstrip:       { ret: 'str',                  sig: 'fn lstrip(chars: str = None) -> str' },
        rstrip:       { ret: 'str',                  sig: 'fn rstrip(chars: str = None) -> str' },
        split:        { ret: 'list[str]',            sig: 'fn split(sep: str = None, maxsplit: int = -1) -> list[str]' },
        rsplit:       { ret: 'list[str]',            sig: 'fn rsplit(sep: str = None, maxsplit: int = -1) -> list[str]' },
        splitlines:   { ret: 'list[str]',            sig: 'fn splitlines() -> list[str]' },
        join:         { ret: 'str',                  sig: 'fn join(iterable: any) -> str' },
        find:         { ret: 'int',                  sig: 'fn find(sub: str, start: int = 0, end: int = -1) -> int' },
        rfind:        { ret: 'int',                  sig: 'fn rfind(sub: str, start: int = 0, end: int = -1) -> int' },
        index:        { ret: 'int',                  sig: 'fn index(sub: str, start: int = 0, end: int = -1) -> int' },
        rindex:       { ret: 'int',                  sig: 'fn rindex(sub: str, start: int = 0, end: int = -1) -> int' },
        count:        { ret: 'int',                  sig: 'fn count(sub: str, start: int = 0, end: int = -1) -> int' },
        contains:     { ret: 'bool',                 sig: 'fn contains(sub: str) -> bool' },
        startswith:   { ret: 'bool',                 sig: 'fn startswith(prefix: str) -> bool' },
        endswith:     { ret: 'bool',                 sig: 'fn endswith(suffix: str) -> bool' },
        replace:      { ret: 'str',                  sig: 'fn replace(old: str, new: str, count: int = -1) -> str' },
        removeprefix: { ret: 'str',                  sig: 'fn removeprefix(prefix: str) -> str' },
        removesuffix: { ret: 'str',                  sig: 'fn removesuffix(suffix: str) -> str' },
        format:       { ret: 'str',                  sig: 'fn format(args: any) -> str' },
        isdigit:      { ret: 'bool',                 sig: 'fn isdigit() -> bool' },
        isnumeric:    { ret: 'bool',                 sig: 'fn isnumeric() -> bool' },
        isalpha:      { ret: 'bool',                 sig: 'fn isalpha() -> bool' },
        isalnum:      { ret: 'bool',                 sig: 'fn isalnum() -> bool' },
        isspace:      { ret: 'bool',                 sig: 'fn isspace() -> bool' },
        isupper:      { ret: 'bool',                 sig: 'fn isupper() -> bool' },
        islower:      { ret: 'bool',                 sig: 'fn islower() -> bool' },
        isascii:      { ret: 'bool',                 sig: 'fn isascii() -> bool' },
        isprintable:  { ret: 'bool',                 sig: 'fn isprintable() -> bool' },
        zfill:        { ret: 'str',                  sig: 'fn zfill(width: int) -> str' },
        ljust:        { ret: 'str',                  sig: 'fn ljust(width: int, fillchar: str = " ") -> str' },
        rjust:        { ret: 'str',                  sig: 'fn rjust(width: int, fillchar: str = " ") -> str' },
        center:       { ret: 'str',                  sig: 'fn center(width: int, fillchar: str = " ") -> str' },
        partition:    { ret: 'tuple[str, str, str]', sig: 'fn partition(sep: str) -> tuple[str, str, str]' },
        rpartition:   { ret: 'tuple[str, str, str]', sig: 'fn rpartition(sep: str) -> tuple[str, str, str]' },
        expandtabs:   { ret: 'str',                  sig: 'fn expandtabs(tabsize: int = 8) -> str' },
        encode:       { ret: 'list[int]',            sig: 'fn encode() -> list[int]' },
        chars:        { ret: 'list[str]',            sig: 'fn chars() -> list[str]' },
        ord:          { ret: 'int',                  sig: 'fn ord() -> int' },
        match:        { ret: 'Option[str]',          sig: 'fn match(pattern: str, flags: str = "") -> Option[str]' },
        search:       { ret: 'Option[str]',          sig: 'fn search(pattern: str, flags: str = "") -> Option[str]' },
        findall:      { ret: 'list[str]',            sig: 'fn findall(pattern: str, flags: str = "") -> list[str]' },
        sub:          { ret: 'str',                  sig: 'fn sub(pattern: str, repl: str, count: int = 0, flags: str = "") -> str' },
        regex_split:  { ret: 'list[str]',            sig: 'fn regex_split(pattern: str, maxsplit: int = 0, flags: str = "") -> list[str]' },
    },
    list: {
        append:  { ret: 'None',  sig: 'fn append(x: any) -> None' },
        extend:  { ret: 'None',  sig: 'fn extend(iterable: any) -> None' },
        insert:  { ret: 'None',  sig: 'fn insert(i: int, x: any) -> None' },
        remove:  { ret: 'None',  sig: 'fn remove(x: any) -> None' },
        pop:     { ret: 'any',   sig: 'fn pop(i: int = -1) -> any' },
        clear:   { ret: 'None',  sig: 'fn clear() -> None' },
        index:   { ret: 'int',   sig: 'fn index(x: any) -> int' },
        count:   { ret: 'int',   sig: 'fn count(x: any) -> int' },
        sort:    { ret: 'None',  sig: 'fn sort(key: any = None, reverse: bool = False) -> None' },
        reverse: { ret: 'None',  sig: 'fn reverse() -> None' },
        copy:    { ret: 'list',  sig: 'fn copy() -> list' },
    },
    dict: {
        get:        { ret: 'any',   sig: 'fn get(key: any, default: any = None) -> any' },
        keys:       { ret: 'list',  sig: 'fn keys() -> list' },
        key:        { ret: 'list',  sig: 'fn key() -> list' },
        values:     { ret: 'list',  sig: 'fn values() -> list' },
        items:      { ret: 'list',  sig: 'fn items() -> list' },
        update:     { ret: 'None',  sig: 'fn update(other: dict) -> None' },
        pop:        { ret: 'any',   sig: 'fn pop(key: any, default: any = None) -> any' },
        clear:      { ret: 'None',  sig: 'fn clear() -> None' },
        copy:       { ret: 'dict',  sig: 'fn copy() -> dict' },
        setdefault: { ret: 'any',   sig: 'fn setdefault(key: any, default: any = None) -> any' },
    },
    set: {
        add:                  { ret: 'None', sig: 'fn add(x: any) -> None' },
        remove:               { ret: 'None', sig: 'fn remove(x: any) -> None' },
        discard:              { ret: 'None', sig: 'fn discard(x: any) -> None' },
        pop:                  { ret: 'any',  sig: 'fn pop() -> any' },
        clear:                { ret: 'None', sig: 'fn clear() -> None' },
        copy:                 { ret: 'set',  sig: 'fn copy() -> set' },
        union:                { ret: 'set',  sig: 'fn union(other: set) -> set' },
        intersection:         { ret: 'set',  sig: 'fn intersection(other: set) -> set' },
        difference:           { ret: 'set',  sig: 'fn difference(other: set) -> set' },
        symmetric_difference: { ret: 'set',  sig: 'fn symmetric_difference(other: set) -> set' },
        issubset:             { ret: 'bool', sig: 'fn issubset(other: set) -> bool' },
        issuperset:           { ret: 'bool', sig: 'fn issuperset(other: set) -> bool' },
    },
};

export const LANG_KEYWORDS = [
    'let', 'mut', 'const', 'fn', 'gen', 'class', 'trait', 'new_type',
    'return', 'if', 'elif', 'else', 'for', 'while', 'match', 'case',
    'and', 'or', 'not', 'in', 'is', 'True', 'False', 'None',
    'self', 'Self', 'static', 'freeze', 'block',
    'block_return', 'loop_yield', 'break', 'continue', 'yield', 'pass',
    'import', 'enumerate', 'zip',
    'public', 'private', 'protected',
    'uint',
];

export const BUILTIN_TYPE_NAMES: ReadonlySet<string> = new Set([
    'int', 'uint', 'float', 'str', 'bool',
    'list', 'dict', 'set', 'tuple', 'bytes',
    'slice', 'path', 'pointer',
    'any', 'Any', 'Union', 'Option', 'Optional',
    'Self', 'object', 'type',
]);
